export const MOVIE_LIST = "MOVIE_LIST";
export const MOVIE_LIST_IS_LOADING = "MOVIE_LIST_IS_LOADIN";
export const MOVIE_LIST_ERROR = "MOVIE_LIST_ERROR";
export const SET_VISIBILITY_FILTER = "SET_VISIBILITY_FILTER";